title: Harry Singh
author: Harry Singh
email: hardev0a0@gmail.com
description: >-
  Lead Software Engineer
baseurl: ""
url: "https://harrysingh.xyz"
github_username: badass-commits
linkedin_username: hardev-singh-805397277
show_excerpts: true
permalink: pretty
exclude: ['README.md']

header_pages:
  - about.md

projects:
  - Finance-Tracker
  - lara-notifications
  - laravel-custom-validation
  - laravel-rest-api
  - react-laravel-jwt-auth
  - twilio-google-sheet-integration

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-octicons
